/**
 * Create by fenglei.li on 2017/7/13
 */

//公共
export const CHANGE_LEFTNAV_STATUS = 'CHANGE_LEFTNAV_STATUS'

// 设置用户信息
export const SET_USERINFO = 'SET_USERINFO'
// 设置用户收藏的素材列表
export const SET_COLLECTEDMATERIALS = 'SET_COLLECTEDMATERIALS'
// 添加素材收藏id
export const SET_ADDCOLLECTEDMATERIALID = 'SET_ADDCOLLECTEDMATERIALID'
// 删除收藏素材
export const SET_REMOVECOLLECTEDMATERIALID = 'SET_REMOVECOLLECTEDMATERIALID'
// 设置登录状态
export const SET_ISLOGIN = 'SET_ISLOGIN'
// 设置团队ID
export const SET_TEAMID = 'SET_TEAMID'
// 设置登录注册显示
export const SET_LOGREG_SHOW = 'SET_LOGREG_SHOW'
// 设置第三方登录iframe
export const SET_IFRAME_SHOW = 'SET_IFRAME_SHOW'
export const SET_IFRAME_URL = 'SET_IFRAME_URL'
// 设置对话框显示
export const SET_DIALOG_SHOW = 'SET_DIALOG_SHOW'
// 设置错误弹窗显示
export const SET_ERROR_SHOW = 'SET_ERROR_SHOW'
// 设置文字临时颜色
export const SET_FONT_COLOR = 'SET_FONT_COLOR'

// 设置团队信息
export const SET_TEAMINFO = 'SET_TEAMINFO'
export const SET_TEAMSTAMP = 'SET_TEAMSTAMP'

/**
 * api
 */
// 设置apiInfo
export const SET_API_TYPE = 'SET_API_TYPE'
export const SET_API_INFO = 'SET_API_INFO'
export const SET_API_TOKEN = 'SET_API_TOKEN'
export const SET_API_HREF = 'SET_API_HREF'

/**
 * design
 */
// 设置designInfo
export const SET_DESIGNINFO = 'SET_DESIGNINFO'
export const SET_DESIGNWHWITHUNIT = 'SET_DESIGNWHWITHUNIT'
export const SET_DESIGNSHARESTATE = 'SET_DESIGNSHARESTATE'
export const SET_ISBLEED = 'SET_ISBLEED'
export const SET_BLANK_CLICK = 'SET_BLANK_CLICK'
export const SET_DESIGN_TITLE = 'SET_DESIGN_TITLE'
export const SET_WINDOW_RESIZE = 'SET_WINDOW_RESIZE'
export const SET_TEMPLATE_INFO = 'SET_TEMPLATE_INFO'

// 公共调用ColorPicker
export const SET_COLORPICKER_SHOW = 'SET_COLORPICKER_SHOW'
export const SET_COLORPICKER_STATUS = 'SET_COLORPICKER_STATUS'

// 左侧添加元素
export const SET_LEFTPANEL_ADDELEMENT_FLOG = 'SET_LEFTPANEL_ADDELEMENT_FLOG'
export const SET_LEFTPANEL_ADDELEMENT_DATA = 'SET_LEFTPANEL_ADDELEMENT_DATA'
export const SET_LEFTPANEL_ADDELEMENT_TEMP = 'SET_LEFTPANEL_ADDELEMENT_TEMP'

// page
export const SET_PAGESJSON = 'SET_PAGESJSON'

export const SET_PAGE_WIDTH = 'SET_PAGE_WIDTH'

export const SET_PAGE_HEIGHT = 'SET_PAGE_HEIGHT'

export const SET_FOCUS_PAGE_INDEX = 'SET_FOCUS_PAGE_INDEX'

export const SET_PAGE_ID_LIST = 'SET_PAGE_ID_LIST'

export const SET_PAGE_READY = 'SET_PAGE_READY'

export const SET_PAGE_SCALE = 'SET_PAGE_SCALE'

export const SET_DEFAULT_PAGE_SCALE = 'SET_DEFAULT_PAGE_SCALE'

export const SET_MAX_PAGE = 'SET_MAX_PAGE'

export const SET_PAGE_BLANK = 'SET_PAGE_BLANK'

export const SET_PAGE_POSITION = 'SET_PAGE_POSITION'

export const SET_DEFAULT_PAGE_POSITION = 'SET_DEFAULT_PAGE_POSITION'

export const SET_PAGE_RECT = 'SET_PAGE_RECT'

export const SET_ELE_DRAGGING = 'SET_ELE_DRAGGING'

export const SET_PAGE_PREVIEW = 'SET_PAGE_PREVIEW'

export const SET_PAGE_CENTER = 'SET_PAGE_CENTER'

export const SET_WIDE_PAGE_STYLE_LIST = 'SET_WIDE_PAGE_STYLE_LIST'

export const SET_STRAIT_PAGE_STYLE_LIST = 'SET_STRAIT_PAGE_STYLE_LIST'

export const SET_PAGE_MOVE_MOUSEDOWN = 'SET_PAGE_MOVE_MOUSEDOWN'

export const SET_CIRCLE_SELECT_ELEMENTS = 'SET_CIRCLE_SELECT_ELEMENTS'

export const SET_CIRCLE_SELECT_ELEMENTS_NOW = 'SET_CIRCLE_SELECT_ELEMENTS_NOW'

// pageNavigator
export const SET_PAGE_NAVIGATOR_THUMB = 'SET_PAGE_NAVIGATOR_THUMB'

// pageWrap
export const SET_PAGE_WRAP_RECT = 'SET_PAGE_WRAP_RECT'

// pageList
export const SET_PAGELIST_CLOSE = 'SET_PAGELIST_CLOSE'

export const SET_PAGE_THUMB_LIST = 'SET_PAGE_THUMB_LIST'

export const SET_DESIGN_SAVE_TIME = 'SET_DESIGN_SAVE_TIME'

export const SET_ALL_PAGE_SAVING = 'SET_ALL_PAGE_SAVING'

export const SET_INDEX_PAGE_SAVING = 'SET_INDEX_PAGE_SAVING'

export const SET_WIDE_PAGE_HEIGHT = 'SET_WIDE_PAGE_HEIGHT'

// rightPanel
export const SET_RIGHT_PANEL_WIDTH = 'SET_RIGHT_PANEL_WIDTH'

// leftPanel
export const SET_LEFT_PANEL_CLOSE = 'SET_LEFT_PANEL_CLOSE'
export const SET_LEFT_PANEL_INDEX = 'SET_LEFT_PANEL_INDEX'
export const SET_LEFT_PANEL_SEARCH_TYPE = 'SET_LEFT_PANEL_SEARCH_TYPE'
export const SET_SHOWFILTER = 'SET_SHOWFILTER'
export const SET_QRCODESHOW = 'SET_QRCODESHOW'
export const SET_QRCODEURL = 'SET_QRCODEURL'
export const SET_TEMPLATEIMGURL = 'SET_TEMPLATEIMGURL'
export const SET_TEMPLATECHANGE = 'SET_TEMPLATECHANGE'
export const SET_IMGUPLOAD = 'SET_IMGUPLOAD'
export const SET_LEFT_PANEL_MENU_LIST = 'SET_LEFT_PANEL_MENU_LIST'


// elements
export const SET_ELEMENTS = 'SET_ELEMENTS'
export const SET_NEW_ADD_ELE_ID = 'SET_NEW_ADD_ELE_ID'
export const SET_SVG_INIT ='SET_SVG_INIT'
/*
 * 加载状态
 */
// 功能页layout加载状态设置
export const SET_LAYOUT_ONLOAD = 'SET_LAYOUT_ONLOAD'
//提示信息
export const SET_MESSAGE_SHOW = 'SET_MESSAGE_SHOW'

// guideLine
export const SET_NOT_FOCUS_ELE_RECT_LIST = 'SET_NOT_FOCUS_ELE_RECT_LIST'

export const SET_GUIDE_LINE_SHOW = 'SET_GUIDE_LINE_SHOW'

export const SET_GUIDE_LINE_FOCUS_ELE = 'SET_GUIDE_LINE_FOCUS_ELE'

// key
export const SET_SPACE_KEY_DOWN = 'SET_SPACE_KEY_DOWN'
export const SET_CTRL_KEY_DOWN = 'SET_CTRL_KEY_DOWN'
export const SET_SHIFT_KEY_DOWN = 'SET_SHIFT_KEY_DOWN'
export const SET_META_KEY_DOWN = 'SET_META_KEY_DOWN'
//header
export const SET_SAVETIMES = 'SET_SAVETIMES'
export const SET_SAVESUCCESSMESSAGEFLAG = 'SET_SAVESUCCESSMESSAGEFLAG'
